name = "project-cymric"
# type = "javascript" is required to use the `[build]` section
type = "javascript"
workers_dev = true
account_id = ""
route = ""
zone_id = ""
compatibility_date = "2022-01-12"

[build.upload]
# Upload the code directly from the src directory.
dir = "src"
# The "modules" upload format is required for all projects that export a Durable Objects class
format = "modules"
main = "./index.mjs"

[durable_objects]
bindings = [{name = "SCHEDULE", class_name = "Schedule"}]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["Schedule"]
